require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DepreciationMethodsController do

  # This should return the minimal set of attributes required to create a valid
  # DepreciationMethod. As you add validations to DepreciationMethod, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "description" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DepreciationMethodsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all depreciation_methods as @depreciation_methods" do
      depreciation_method = DepreciationMethod.create! valid_attributes
      get :index, {}, valid_session
      assigns(:depreciation_methods).should eq([depreciation_method])
    end
  end

  describe "GET show" do
    it "assigns the requested depreciation_method as @depreciation_method" do
      depreciation_method = DepreciationMethod.create! valid_attributes
      get :show, {:id => depreciation_method.to_param}, valid_session
      assigns(:depreciation_method).should eq(depreciation_method)
    end
  end

  describe "GET new" do
    it "assigns a new depreciation_method as @depreciation_method" do
      get :new, {}, valid_session
      assigns(:depreciation_method).should be_a_new(DepreciationMethod)
    end
  end

  describe "GET edit" do
    it "assigns the requested depreciation_method as @depreciation_method" do
      depreciation_method = DepreciationMethod.create! valid_attributes
      get :edit, {:id => depreciation_method.to_param}, valid_session
      assigns(:depreciation_method).should eq(depreciation_method)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DepreciationMethod" do
        expect {
          post :create, {:depreciation_method => valid_attributes}, valid_session
        }.to change(DepreciationMethod, :count).by(1)
      end

      it "assigns a newly created depreciation_method as @depreciation_method" do
        post :create, {:depreciation_method => valid_attributes}, valid_session
        assigns(:depreciation_method).should be_a(DepreciationMethod)
        assigns(:depreciation_method).should be_persisted
      end

      it "redirects to the created depreciation_method" do
        post :create, {:depreciation_method => valid_attributes}, valid_session
        response.should redirect_to(DepreciationMethod.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved depreciation_method as @depreciation_method" do
        # Trigger the behavior that occurs when invalid params are submitted
        DepreciationMethod.any_instance.stub(:save).and_return(false)
        post :create, {:depreciation_method => { "description" => "invalid value" }}, valid_session
        assigns(:depreciation_method).should be_a_new(DepreciationMethod)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DepreciationMethod.any_instance.stub(:save).and_return(false)
        post :create, {:depreciation_method => { "description" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested depreciation_method" do
        depreciation_method = DepreciationMethod.create! valid_attributes
        # Assuming there are no other depreciation_methods in the database, this
        # specifies that the DepreciationMethod created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DepreciationMethod.any_instance.should_receive(:update_attributes).with({ "description" => "MyString" })
        put :update, {:id => depreciation_method.to_param, :depreciation_method => { "description" => "MyString" }}, valid_session
      end

      it "assigns the requested depreciation_method as @depreciation_method" do
        depreciation_method = DepreciationMethod.create! valid_attributes
        put :update, {:id => depreciation_method.to_param, :depreciation_method => valid_attributes}, valid_session
        assigns(:depreciation_method).should eq(depreciation_method)
      end

      it "redirects to the depreciation_method" do
        depreciation_method = DepreciationMethod.create! valid_attributes
        put :update, {:id => depreciation_method.to_param, :depreciation_method => valid_attributes}, valid_session
        response.should redirect_to(depreciation_method)
      end
    end

    describe "with invalid params" do
      it "assigns the depreciation_method as @depreciation_method" do
        depreciation_method = DepreciationMethod.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DepreciationMethod.any_instance.stub(:save).and_return(false)
        put :update, {:id => depreciation_method.to_param, :depreciation_method => { "description" => "invalid value" }}, valid_session
        assigns(:depreciation_method).should eq(depreciation_method)
      end

      it "re-renders the 'edit' template" do
        depreciation_method = DepreciationMethod.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DepreciationMethod.any_instance.stub(:save).and_return(false)
        put :update, {:id => depreciation_method.to_param, :depreciation_method => { "description" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested depreciation_method" do
      depreciation_method = DepreciationMethod.create! valid_attributes
      expect {
        delete :destroy, {:id => depreciation_method.to_param}, valid_session
      }.to change(DepreciationMethod, :count).by(-1)
    end

    it "redirects to the depreciation_methods list" do
      depreciation_method = DepreciationMethod.create! valid_attributes
      delete :destroy, {:id => depreciation_method.to_param}, valid_session
      response.should redirect_to(depreciation_methods_url)
    end
  end

end
