require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SparepartTransDocOutsController do

  # This should return the minimal set of attributes required to create a valid
  # SparepartTransDocOut. As you add validations to SparepartTransDocOut, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "doc_no" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # SparepartTransDocOutsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all sparepart_trans_doc_outs as @sparepart_trans_doc_outs" do
      sparepart_trans_doc_out = SparepartTransDocOut.create! valid_attributes
      get :index, {}, valid_session
      assigns(:sparepart_trans_doc_outs).should eq([sparepart_trans_doc_out])
    end
  end

  describe "GET show" do
    it "assigns the requested sparepart_trans_doc_out as @sparepart_trans_doc_out" do
      sparepart_trans_doc_out = SparepartTransDocOut.create! valid_attributes
      get :show, {:id => sparepart_trans_doc_out.to_param}, valid_session
      assigns(:sparepart_trans_doc_out).should eq(sparepart_trans_doc_out)
    end
  end

  describe "GET new" do
    it "assigns a new sparepart_trans_doc_out as @sparepart_trans_doc_out" do
      get :new, {}, valid_session
      assigns(:sparepart_trans_doc_out).should be_a_new(SparepartTransDocOut)
    end
  end

  describe "GET edit" do
    it "assigns the requested sparepart_trans_doc_out as @sparepart_trans_doc_out" do
      sparepart_trans_doc_out = SparepartTransDocOut.create! valid_attributes
      get :edit, {:id => sparepart_trans_doc_out.to_param}, valid_session
      assigns(:sparepart_trans_doc_out).should eq(sparepart_trans_doc_out)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SparepartTransDocOut" do
        expect {
          post :create, {:sparepart_trans_doc_out => valid_attributes}, valid_session
        }.to change(SparepartTransDocOut, :count).by(1)
      end

      it "assigns a newly created sparepart_trans_doc_out as @sparepart_trans_doc_out" do
        post :create, {:sparepart_trans_doc_out => valid_attributes}, valid_session
        assigns(:sparepart_trans_doc_out).should be_a(SparepartTransDocOut)
        assigns(:sparepart_trans_doc_out).should be_persisted
      end

      it "redirects to the created sparepart_trans_doc_out" do
        post :create, {:sparepart_trans_doc_out => valid_attributes}, valid_session
        response.should redirect_to(SparepartTransDocOut.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved sparepart_trans_doc_out as @sparepart_trans_doc_out" do
        # Trigger the behavior that occurs when invalid params are submitted
        SparepartTransDocOut.any_instance.stub(:save).and_return(false)
        post :create, {:sparepart_trans_doc_out => { "doc_no" => "invalid value" }}, valid_session
        assigns(:sparepart_trans_doc_out).should be_a_new(SparepartTransDocOut)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SparepartTransDocOut.any_instance.stub(:save).and_return(false)
        post :create, {:sparepart_trans_doc_out => { "doc_no" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested sparepart_trans_doc_out" do
        sparepart_trans_doc_out = SparepartTransDocOut.create! valid_attributes
        # Assuming there are no other sparepart_trans_doc_outs in the database, this
        # specifies that the SparepartTransDocOut created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SparepartTransDocOut.any_instance.should_receive(:update_attributes).with({ "doc_no" => "MyString" })
        put :update, {:id => sparepart_trans_doc_out.to_param, :sparepart_trans_doc_out => { "doc_no" => "MyString" }}, valid_session
      end

      it "assigns the requested sparepart_trans_doc_out as @sparepart_trans_doc_out" do
        sparepart_trans_doc_out = SparepartTransDocOut.create! valid_attributes
        put :update, {:id => sparepart_trans_doc_out.to_param, :sparepart_trans_doc_out => valid_attributes}, valid_session
        assigns(:sparepart_trans_doc_out).should eq(sparepart_trans_doc_out)
      end

      it "redirects to the sparepart_trans_doc_out" do
        sparepart_trans_doc_out = SparepartTransDocOut.create! valid_attributes
        put :update, {:id => sparepart_trans_doc_out.to_param, :sparepart_trans_doc_out => valid_attributes}, valid_session
        response.should redirect_to(sparepart_trans_doc_out)
      end
    end

    describe "with invalid params" do
      it "assigns the sparepart_trans_doc_out as @sparepart_trans_doc_out" do
        sparepart_trans_doc_out = SparepartTransDocOut.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SparepartTransDocOut.any_instance.stub(:save).and_return(false)
        put :update, {:id => sparepart_trans_doc_out.to_param, :sparepart_trans_doc_out => { "doc_no" => "invalid value" }}, valid_session
        assigns(:sparepart_trans_doc_out).should eq(sparepart_trans_doc_out)
      end

      it "re-renders the 'edit' template" do
        sparepart_trans_doc_out = SparepartTransDocOut.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SparepartTransDocOut.any_instance.stub(:save).and_return(false)
        put :update, {:id => sparepart_trans_doc_out.to_param, :sparepart_trans_doc_out => { "doc_no" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested sparepart_trans_doc_out" do
      sparepart_trans_doc_out = SparepartTransDocOut.create! valid_attributes
      expect {
        delete :destroy, {:id => sparepart_trans_doc_out.to_param}, valid_session
      }.to change(SparepartTransDocOut, :count).by(-1)
    end

    it "redirects to the sparepart_trans_doc_outs list" do
      sparepart_trans_doc_out = SparepartTransDocOut.create! valid_attributes
      delete :destroy, {:id => sparepart_trans_doc_out.to_param}, valid_session
      response.should redirect_to(sparepart_trans_doc_outs_url)
    end
  end

end
