require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe TransDocOutTypesController do

  # This should return the minimal set of attributes required to create a valid
  # TransDocOutType. As you add validations to TransDocOutType, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "key" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # TransDocOutTypesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all trans_doc_out_types as @trans_doc_out_types" do
      trans_doc_out_type = TransDocOutType.create! valid_attributes
      get :index, {}, valid_session
      assigns(:trans_doc_out_types).should eq([trans_doc_out_type])
    end
  end

  describe "GET show" do
    it "assigns the requested trans_doc_out_type as @trans_doc_out_type" do
      trans_doc_out_type = TransDocOutType.create! valid_attributes
      get :show, {:id => trans_doc_out_type.to_param}, valid_session
      assigns(:trans_doc_out_type).should eq(trans_doc_out_type)
    end
  end

  describe "GET new" do
    it "assigns a new trans_doc_out_type as @trans_doc_out_type" do
      get :new, {}, valid_session
      assigns(:trans_doc_out_type).should be_a_new(TransDocOutType)
    end
  end

  describe "GET edit" do
    it "assigns the requested trans_doc_out_type as @trans_doc_out_type" do
      trans_doc_out_type = TransDocOutType.create! valid_attributes
      get :edit, {:id => trans_doc_out_type.to_param}, valid_session
      assigns(:trans_doc_out_type).should eq(trans_doc_out_type)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new TransDocOutType" do
        expect {
          post :create, {:trans_doc_out_type => valid_attributes}, valid_session
        }.to change(TransDocOutType, :count).by(1)
      end

      it "assigns a newly created trans_doc_out_type as @trans_doc_out_type" do
        post :create, {:trans_doc_out_type => valid_attributes}, valid_session
        assigns(:trans_doc_out_type).should be_a(TransDocOutType)
        assigns(:trans_doc_out_type).should be_persisted
      end

      it "redirects to the created trans_doc_out_type" do
        post :create, {:trans_doc_out_type => valid_attributes}, valid_session
        response.should redirect_to(TransDocOutType.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved trans_doc_out_type as @trans_doc_out_type" do
        # Trigger the behavior that occurs when invalid params are submitted
        TransDocOutType.any_instance.stub(:save).and_return(false)
        post :create, {:trans_doc_out_type => { "key" => "invalid value" }}, valid_session
        assigns(:trans_doc_out_type).should be_a_new(TransDocOutType)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        TransDocOutType.any_instance.stub(:save).and_return(false)
        post :create, {:trans_doc_out_type => { "key" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested trans_doc_out_type" do
        trans_doc_out_type = TransDocOutType.create! valid_attributes
        # Assuming there are no other trans_doc_out_types in the database, this
        # specifies that the TransDocOutType created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        TransDocOutType.any_instance.should_receive(:update_attributes).with({ "key" => "MyString" })
        put :update, {:id => trans_doc_out_type.to_param, :trans_doc_out_type => { "key" => "MyString" }}, valid_session
      end

      it "assigns the requested trans_doc_out_type as @trans_doc_out_type" do
        trans_doc_out_type = TransDocOutType.create! valid_attributes
        put :update, {:id => trans_doc_out_type.to_param, :trans_doc_out_type => valid_attributes}, valid_session
        assigns(:trans_doc_out_type).should eq(trans_doc_out_type)
      end

      it "redirects to the trans_doc_out_type" do
        trans_doc_out_type = TransDocOutType.create! valid_attributes
        put :update, {:id => trans_doc_out_type.to_param, :trans_doc_out_type => valid_attributes}, valid_session
        response.should redirect_to(trans_doc_out_type)
      end
    end

    describe "with invalid params" do
      it "assigns the trans_doc_out_type as @trans_doc_out_type" do
        trans_doc_out_type = TransDocOutType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TransDocOutType.any_instance.stub(:save).and_return(false)
        put :update, {:id => trans_doc_out_type.to_param, :trans_doc_out_type => { "key" => "invalid value" }}, valid_session
        assigns(:trans_doc_out_type).should eq(trans_doc_out_type)
      end

      it "re-renders the 'edit' template" do
        trans_doc_out_type = TransDocOutType.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        TransDocOutType.any_instance.stub(:save).and_return(false)
        put :update, {:id => trans_doc_out_type.to_param, :trans_doc_out_type => { "key" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested trans_doc_out_type" do
      trans_doc_out_type = TransDocOutType.create! valid_attributes
      expect {
        delete :destroy, {:id => trans_doc_out_type.to_param}, valid_session
      }.to change(TransDocOutType, :count).by(-1)
    end

    it "redirects to the trans_doc_out_types list" do
      trans_doc_out_type = TransDocOutType.create! valid_attributes
      delete :destroy, {:id => trans_doc_out_type.to_param}, valid_session
      response.should redirect_to(trans_doc_out_types_url)
    end
  end

end
